# Generated by Django 3.2.8 on 2021-12-16 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
                ('name', models.CharField(max_length=50, verbose_name='Drug name')),
                ('description', models.TextField(verbose_name='Description')),
                ('company', models.CharField(max_length=50, verbose_name='Company manufacturer')),
                ('cost', models.IntegerField(verbose_name='Cost')),
                ('discount', models.BooleanField(verbose_name='Discount')),
                ('discount_cost', models.IntegerField(default=0, verbose_name='Discount cost')),
                ('special', models.BooleanField(default=False, verbose_name='Special')),
                ('special_cost', models.IntegerField(default=0, verbose_name='Special cost')),
                ('category', models.CharField(choices=[('Antibiotics', 'Antibiotics'), ('Antiseptics', 'Antiseptics'), ('Painkillers', 'Painkillers'), ('Against cough', 'Against cough'), ('For baby', 'For baby'), ('Vitamins', 'Vitamins')], max_length=15)),
                ('quantity', models.IntegerField(default=1)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('payment', models.CharField(blank=True, max_length=20, null=True)),
                ('items', models.ManyToManyField(to='pharmacy.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
