# Generated by Django 3.2.8 on 2021-11-27 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.CharField(choices=[('AB', 'Antibiotics'), ('AS', 'Antiseptics'), ('PK', 'Painkillers'), ('AC', 'Against cough'), ('FB', 'For baby'), ('V', 'Vitamins')], default='Antibiotics', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='Discount'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.good')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('goods', models.ManyToManyField(to='pharmacy.OrderGood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
