# Generated by Django 3.2.8 on 2021-12-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20211203_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='special',
            field=models.BooleanField(default=False, verbose_name='Special'),
        ),
        migrations.AddField(
            model_name='item',
            name='special_cost',
            field=models.IntegerField(default=0, verbose_name='Special cost'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Antibiotics', 'Antibiotics'), ('Antiseptics', 'Antiseptics'), ('Painkillers', 'Painkillers'), ('Against cough', 'Against cough'), ('For baby', 'For baby'), ('Vitamins', 'Vitamins')], max_length=15),
        ),
    ]
