# Generated by Django 3.2.8 on 2021-11-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20211127_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
