# Generated by Django 3.2.8 on 2021-11-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_good_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='discount_cost',
            field=models.IntegerField(default=0, verbose_name='Discount cost'),
        ),
        migrations.AddField(
            model_name='good',
            name='slug',
            field=models.SlugField(default='test-product'),
            preserve_default=False,
        ),
    ]
